### ISSUE TITLE
Плохая карточка отображения информации о фильме

### ISSUE THREAD

**Issue by CookLe123** [Coercivity/RollGO#28]
Маленькая картинка (постер). Необходимо увеличить картинку ЛИБО расширить её по всей карточке фильма на заднем фоне. Надписи с рейтингом приравнять к правой части. Для оценок с кинопоиска и IMDB - добавить иконки (цифра+звезда) для удобности расположения напротив надписи. Сами надписи приравнять по одной полосе.

**Comment by slavoyar** [comment]
@CookLe123 Нарисуй пример в фигме как должно выглядеть

**Comment by CookLe123** [comment]
![FilmCard](https://github.com/Coercivity/RollGO/assets/129439274/5f3966db-b467-4102-b1fa-cd806d6d9d36)
![FilmCard2](https://github.com/Coercivity/RollGO/assets/129439274/09b0bc17-fde0-4770-86ec-c0f377cc26e7)

**Comment by slavoyar** [comment]
@CookLe123 Постеры будут браться с кинопоиска, они все в портретной ориентации.

![image](https://github.com/Coercivity/RollGO/assets/37935471/9571b180-8adb-4af2-9d26-f2221ab1d815)
